### ISSUE TITLE
No money recieved 

### ISSUE THREAD

**Issue by uttufy** [yatinas/Foundation-bank#1]
This is regrading to the transaction Mr. Ambani made which was suppose to be received by me.
But My bank account still showing me no money is been transferred to my account and that I am still a gareeb.
Please sir resolve this issue asap because I have to pay my AKTU exam fees + Reevaluation fees

**Comment by yatinas** [comment]
our management team has recorded your complaint we will try to solve it as
soon as possible and we will get back to you shortly.

**Comment by uttufy** [comment]
Thanks issue is resolved now.
All the best for the exams
